// Import GraphQL schema definition helper from Apollo
const { gql } = require("apollo-server-express");

// Define GraphQL type definitions related to the User model and authentication
const userTypeDefs = gql`
  # ===========================
  # User Type Definition
  # ===========================
  type User {
    id: ID! # Unique user ID (auto-generated by MongoDB)
    username: String! # Username (required)
    email: String! # Email address (required)
    password: String! # Hashed password (required)
    created_at: String! # Timestamp of when the user was created
    updated_at: String! # Timestamp of last update
  }

  # ===========================
  # Auth Payload Wrapper
  # Used for login responses
  # ===========================
  type AuthPayload {
    token: String # JWT token returned upon successful login
    user: User # The logged-in user's data
  }

  # ===========================
  # Query Definitions
  # ===========================
  type Query {
    # Get currently logged-in user from token
    me: User
  }

  # ===========================
  # Mutation Definitions
  # ===========================
  type Mutation {
    # Register a new user
    signup(username: String!, email: String!, password: String!): User

    # Authenticate a user and return token + user info
    login(username: String!, password: String!): AuthPayload

    # Clear auth session (if using cookie-based session)
    logout: Boolean
  }
`;

// Export the schema to be used in Apollo Server
module.exports = userTypeDefs;
